# Generated by Django 5.1.1 on 2024-09-11 13:47

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[home.validators.file_size])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
