# Generated by Django 5.1.1 on 2024-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
