# Generated by Django 5.1.1 on 2024-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_video_language_video_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
